[global]
# the name will validate join cluster by same name
name = "anyindex"
# your server ip for connect, you can use -i in rags to set it
ip = "127.0.0.1"
# log path , If you are in a production environment, You'd better set absolute paths
log = "logs/"
# this config for all start model
log_level = "debug"
# size for max log file size default is 128 MB
log_limit_bytes = 134217728
# the log file num  , default is 100
log_limit_bytes = 100


[router]
# port for server
http_port = 8080

[ps]
#set zone num, default is 0
zone_id = 0
# you data save to disk path ,If you are in a production environment, You'd better set absolute paths
data = "data/"
# port for server
rpc_port = 9090
# simba to flush data how long sleep 
flush_sleep_sec = 3;

[[masters]]
# master ip for service
ip = "127.0.0.1"
# port for server
http_port = 7070
# master data path for meta
data = "data/meta/"
